**Level:1 Easy**

WAF to print Hello Word


In [ ]:
def name():
    print("Hello World")
name()

WAP to check if a user - input number is even or odd

In [ ]:
num = int(input("Enter number:"))
if num % 2 ==0:
    print(f"{num} is Even")
else:
    print(f"{num} is odd")
    


WAF to print sum,diffrence and product

In [ ]:
def operation(a,b):
    print(f"Sum:{a+b}")
    print(f"Diffrence:{a-b}")
    print(f"Product: {a*b}")

operation(12,5)
   

WAP to convert Celcius to Fahrenheit using the formula F= (C*9/5)+32

In [ ]:
celcius = float(input("Enter Celcius:"))

fahrenheit = (celcius*9/5) + 32
print(f"Fahrenheit of {celcius} is: {fahrenheit}")

WAF to find largest number in a list without using max() function

In [ ]:
list_num = [12,34,56,78]

def find_large_num():
    max_num = list_num[0]
    for num in list_num:
        if num>max_num:
            max_num = num
    print(max_num)
find_large_num()

WAF to calculate the sum of list

In [ ]:
def sum_list(list):
    print(sum(list))
sum_list([12,34,56,78,90])

Create a function that reverse string


In [ ]:
def reverse_string(str):
    rev_string = str[::-1]
    print(rev_string)
reverse_string("Hello")

WAP that counts the number of vowel(a,e,i,o,u) in a string

In [ ]:
word = input("Enter word:").capitalize()
count = 0
for char in word:
    if char in ['a','e','i','o','u']:
        count+=1
print(count)

WAP that takes number and perform operation (+,-,*,/,%)

In [ ]:
def operation(a,b):
    print(f"Sum:{a+b}")
    print(f"SUbract:{a-b}")
    print(f"product:{a*b}")
    print(f"Diffrence:{a/b}")
    print(f"Module:{a%b}")

operation(123,234)

WAF to swap number

In [ ]:
def swap(a,b):
    a,b=b,a
    print(f"A:{a}, b:{b}")
swap(4,5)

Write a program to create multiplication table given number upto 10


In [ ]:
def genratetable(n):
    table = ""
    for i in range(1,11):
        table+=f"{n}*{i}={n * i}\n"
    print(table)
        
for i in range(2,21):
    genratetable(i)
    
   

Given a list [1,2,3,5,5] and print only the first three element


In [ ]:
num = [1,2,3,4,5]

num = num[0:3]
print(num)

WAF to check if a number is x is divisble by y

In [ ]:
def division(x,y):
    if y==0:
        print("Can't devide by 0")
    else:
        print(x/y)
division(12,0)
division(12,4)

WAF to checks if a specific key exist in a dictionary

In [ ]:
data = {
    'Name':'Harsh kumar',
    'Age':19,
    'City':'Patna'
}
def find_key(key):
    if key in data:
        print(data[key])
find_key('City')
find_key('Name')
find_key('Age')

Convert a list with duplicate element into a set to remove duplicates, then convert it back to a list 

In [ ]:
num = [12,34,12,34,56,78]

num =set(num)
print(num)

**Level2:Medium**

WAF to calculate the factorial of a number using while loop

In [3]:
num = int(input("Enter num:"))
fact = 1
i = 1
while (i<=num):
    fact = fact*i
    i+=1
print(fact)



120


WAF that check a string is pallindrome or not

In [12]:
def pallindrome(word):
    if word == word[::-1]:
        print(f"{word} is pallindrome")
    else:
        print(f"{word} is  not pallindrome")

pallindrome('Harsh')


Harsh is  not pallindrome


WAP to genrate the first n number of the fibonacci sequence

In [13]:
i = 0
a,b =0,1

while i < 10:
    print(a)
    a, b = b, a + b
    i = i + 1

0
1
1
2
3
5
8
13
21
34


WAF to check if a number is prime or not!

In [14]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

n = int(input())
print(is_prime(n))


False


WAF to find second largest number in list

In [21]:
n = [12, 20, 30, 40]

def large_num():
    first = second = -1
    for i in n:
        if i > first:
            second = first
            first = i
        elif i > second and i != first:
            second = i
    print(second)

large_num()


30


Create a list of squares of all even number between 1 and 20

In [23]:
square = [i*i for i in range(1,21) if i%2==0]
print(square)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


WAF that takes string and returns a dictonary counting how many time each word appears

In [1]:
def word_count(text):
    counts = {}
    words = text.split()
    for word in words:
        word = word.lower()
        counts[word] = counts.get(word,0)+1
    print(counts)

word_count("my name is my name is my harshu kumar kumar is my harshu kumar")


{'my': 4, 'name': 2, 'is': 3, 'harshu': 2, 'kumar': 3}


FInd the common element between two list

In [2]:
def common_element(list1,list2):
    set1 = set(list1)
    set2 = set(list2)

    common = set1.intersection(set2)
    print(common)
common_element([12,13,14,16],[12,13,45,67]) 

{12, 13}


Merge two dictonary into one

In [7]:
def merge_dict(d1,d2):
    d1.update(d2)
    print(d1)

merge_dict({
    'name':['Harsh','Prince','Aarav','Prashant'],
    'age':[19,18,21,20],
    'city':['Patna','Patna','Patna','Patna']

},{
    'First_name':['Dhananjay','Vaibhav','Anmol','Tannu'],
    'Age':[22,21,21,19],
    'City':['Patna','patna','patna','patna']
})

{'name': ['Harsh', 'Prince', 'Aarav', 'Prashant'], 'age': [19, 18, 21, 20], 'city': ['Patna', 'Patna', 'Patna', 'Patna'], 'First_name': ['Dhananjay', 'Vaibhav', 'Anmol', 'Tannu'], 'Age': [22, 21, 21, 19], 'City': ['Patna', 'patna', 'patna', 'patna']}


WAF that convert the first letter of every word in a sentence to uppercase

In [14]:
def uppercase(letter):
    print(letter.capitalize())
    
uppercase('hello')


Hello


Given 3x3 matrix and calculte its transpose


In [24]:
import numpy as np

def transpose(l1,l2,l3):
    if len(l1)!=3 or len(l2)!=3 or len(l3)!=3:
        raise IndexError("Only 3 element required")
    else:
        matrix = np.array([l1,l2,l3])
        transpose_matrix = matrix.T

        print(f"Orignal matrix:\n {matrix}")
        print(f"transpose matrix:\n {transpose_matrix}")

transpose([2,4,6],[3,4,5],[4,5,6])

Orignal matrix:
 [[2 4 6]
 [3 4 5]
 [4 5 6]]
transpose matrix:
 [[2 3 4]
 [4 4 5]
 [6 5 6]]


WAF that takes integer and returns sum of number

In [28]:
num = int(input("Enter num:"))
sum = 0
for i in range(1,num+1):
    sum = sum+i
print(f"Sum:{sum}")

Sum:10


flatten a list of list

In [ ]:
import numpy as np
def flatten(l1,l2):
    arr = np.array([l1,l2])
    print(arr.flatten())
flatten([1,2],[3,4])

[1 2 3 4]


**Oops**

Create a class car with attributes make,model and year. add method start_engine() that prints the [make] [model]'s engine is running

In [37]:
class Car:
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year
        
    def start_engine(self):
        print(f"{self.make} {self.model}'s engine is running")

C1 = Car('Tata','Safari','2015')
C1.start_engine()


Tata Safari's engine is running


Create a parent class `Animal` with a method `speak()`. create two child classes `Dog` and `Cat` that override `speak()` to return `woof` and `meow` respectively

In [51]:
class Animal:
    def __init__(self,name):
        self.name = name
    def speak(self):
        print(f"{self.name} ")
    
class Dog(Animal):
    def __init__(self,name):
        super().__init__(name)

    def speak(self):
        print(f"The {self.name} is Woof")
        
class cat(Animal):
    def __init__(self, name):
        super().__init__(name)
    def speak(self):
        print(f"The {self.name} is Meow")

A1 = cat('Buddy')
A1.speak()

The Buddy is Meow


Create a class `bankAccount` with **private** attribute _balance. implement method `deposit()` `withdrawal()` and a method to get the current balance ensuring the balance never goes negative .

In [ ]:
class bankAccount:
    def __init__(self,Account_holder,Account_no,balence=0):
        self.Accountholder = Account_holder
        self.Account_no = Account_no
        self.__balence = balence

    
    def deposite(self,Amount):
        self.__balence = self.__balence + Amount
        print(f"₹{Amount} deposite successfully")
        print(f"Your Current balence is {self.__balence}")

    
    def withrawl(self,Amount):
        if Amount > self.__balence:
            print("Insufficient balance! Withdrawal denied.")
        else:
            self.__balence = self.__balence - Amount
            print(f"₹{Amount} Widhrawll successfully")
            print(f"Your Current balence is {self.__balence}")

    def show_balence(self):
        print(f"Your total balence is {self.__balence}")

SBi = bankAccount('Harsh kumar',100491030050501)

SBi.deposite(2000)
SBi.withrawl(500)

SBI = bankAccount('shalini kumari',12344,6205808582)
SBI.deposite(1)
SBI.withrawl(1)


₹2000 deposite successfully
Your Current balence is 2000
₹500 Widhrawll successfully
Your Current balence is 1500
₹1 deposite successfully
Your Current balence is 1
₹1 Widhrawll successfully
Your Current balence is 0


write a class student that initializes with name and grade(a list). Add a method to calculate the average grade

In [13]:
class Student:
    def __init__(self,name,marks):
        self.name = name
        self.marks = marks
    
    def avrage(self):
        return sum(self.marks)/len(self.marks)
    
    def show(self):
        print(f"Average marks obtained by {self.name}: {self.avrage()}")

s1 = Student('Harsh',[23,45,67,89])
s1.show()


Average marks obtained by Harsh: 56.0


Write a function animal_sound(animal_obj) that accepts any object (Dog,Cat,etc.) and calls its speak() method, demonstrating that the function works regardless of the specific class type

In [23]:
class animal:
    def __init__(self,type,sound):
        self.animal_type = type
        self.sound = sound
    
    def speak(self):
        print(f"{self.animal_type} says {self.sound}")

class dog:
    def speak(self):
        print(f"Dog says Woof")

class Cat:
    def speak(self):
        print(f"Cat says meow")

def animal_sound(animal_obj):
    animal_obj.speak()


a1 = animal('Cow','Moo')
b1 = dog()
c1 = Cat()

animal_sound(a1)
animal_sound(b1)
animal_sound(c1)



    


        
        

Cow says Moo
Dog says Woof
Cat says meow


Create a vector class representing a 2D point(x,y). implementation the _str__ method to dispaly it as "(x,y)" and the  _add__ method to allow adding two vectors objects together using + operator

In [25]:
class vector:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    
    def __add__(self,other):
        return vector(self.x+other.x,self.y+other.y)
    def __str__(self):
        return f"Vector: ({self.x},{self.y})"
    
v1 = vector(2,3)
v2 = vector(4,5)

add = v1+v2

print(add)

Vector: (6,8)


Create a class Calculator. Add a static method add(A,B ) that add Two numbers and a class method info() that return a string description of the class

In [27]:
class calculator:

    @staticmethod
    def add(a,b):
        return a+b
    
    @classmethod
    def info(cls):
        return f"{cls.__name__} is a simple calculator class that performs basic operations."
    
result = calculator.add(12,20)
print(f"Addition: {result}")

print(calculator.info())

Addition: 32
calculator is a simple calculator class that performs basic operations.


# Numpy Libraries

**Level 01: Basic**

In [1]:
import numpy as np

Create a 1D array of numbers from 0 to 9

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 3*3 identity matrix

In [17]:
arr = np.eye(3)
arr



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Reshape a 1D array of 12 elements into 3*4 matrix

In [19]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Find the mean,median and standerd deviation of an array

In [22]:
arr = np.array([12,34,56,45,34,56,65,34,23])
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)

print(f"mean:{mean}\nmedian:{median}\nstd:{std}")

mean:39.888888888888886
median:34.0
std:16.134465831081023


Extract all odd number from array

In [ ]:
arr = np.array([12,23,45,67,78])
odds = arr[arr % 2 != 0] 
odds

array([23, 45, 67])

Reverse a 1D array(first element become last)

In [ ]:
arr = np.array([12,34,78,45,32,11])
rev_arr = arr[::-1]
rev_arr

array([11, 32, 45, 78, 34, 12])

Create an array of 10 zeros, but the fifth value is 1

In [25]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Level 02: Medium**

Replace all odd numbers in an array with -1 without changing the original array

In [27]:
arr = np.array([12,34,56,78,90,22,11,23])

fill_odd = np.where(arr %2 !=0, -1,arr)
fill_odd

array([12, 34, 56, 78, 90, 22, -1, -1])

FInd the common items between two arrays

In [29]:
arr1 = np.array([12,34,56,78])
arr2 = np.array([12,34,54,65])

common = np.intersect1d(arr1,arr2)
common

array([12, 34])

Stack two arrays a and b vertically

In [33]:
a = np.array([12,34,56,78])
b = np.array([13,46,79,14])

stack = np.vstack([a,b])
stack

array([[12, 34, 56, 78],
       [13, 46, 79, 14]])

Find the position where element a and b are match

In [37]:
a = np.array([12,34,57,68,90])
b = np.array([12,34,5,68,21])

match = np.where(a == b)
match

(array([0, 1, 3]),)

Normalize a 5*5 random matrix(scale vslue between 0 and 1)

In [40]:
arr = np.random.random((5,5))

arr_norm = (arr-arr.min())/(arr.max()-arr.min())
arr_norm

array([[0.00578554, 0.02965138, 0.99769679, 0.69331366, 0.61443873],
       [1.        , 0.86205684, 0.75808575, 0.        , 0.70799287],
       [0.34351175, 0.64483841, 0.57015483, 0.02601536, 0.4214409 ],
       [0.73213253, 0.61095919, 0.78955333, 0.50722487, 0.40514581],
       [0.95848937, 0.2383072 , 0.59288708, 0.94726439, 0.78027352]])

Create a 2D array with 1 on border and 0 on inside

In [41]:
arr = np.ones((5,5))

arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Get the n largest value of an array

In [42]:
arr = np.array([12,34,56,78])
n= 3
n_largest = np.sort(arr)[-n:]
n_largest

array([34, 56, 78])

**Level 03: Advance**

Compute the dot product two matrices

In [46]:
a = np.ones((3,2))
b = np.ones((2,3))

dot = np.dot(a,b)
dot


array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

FInd the most frequent value in an array

In [ ]:
arr = np.array([1,1,1,2,2,2,3,3,4,5,6,6,6,7,8])
most_frequent = np.bincount(arr).argmax()
most_frequent

np.int64(1)

Create a structured array with "name"(string), age(int), weight(float)

In [54]:
data = np.zeros(3,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})
data['name'] = ['Alice','charlie','harsh']
data['age'] = [20,30,40]

print(data['name'],data['age'])

['Alice' 'charlie' 'harsh'] [20 30 40]
