Create a 1D NumPy array from a Python list.

In [1]:
import numpy as np

In [3]:
list = [1,2,3,4,5]

arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

Create a 2D NumPy array of shape (3, 4) filled with zeros.


In [4]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Create a NumPy array of shape (4, 4) filled with ones.


In [12]:
arr = np.array([[2,3,4,5],[4,5,7,8],[23,45,67,89],[45,67,89,45]])
arr

array([[ 2,  3,  4,  5],
       [ 4,  5,  7,  8],
       [23, 45, 67, 89],
       [45, 67, 89, 45]])

Create an identity matrix of size 5 × 5.

In [14]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create a NumPy array with values from 10 to 50.


In [18]:
arr = np.random.randint(10,50,10).reshape(2,5)
arr

array([[36, 26, 46, 12, 10],
       [41, 30, 14, 28, 49]], dtype=int32)

Create an array of 10 equally spaced values between 0 and 1.


In [ ]:
arr = np.random.rand(10).reshape(2,5)
arr 

array([[0.37046093, 0.09228149, 0.63351999, 0.65516398, 0.83355126],
       [0.99603872, 0.18001184, 0.72694848, 0.15485696, 0.24129701]])

Find the shape, size, and data type of a NumPy array.


In [42]:
arr = np.arange(12).reshape(2,6)
print(arr)
print('\nProperties of Array:-')
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Properties of Array:-
(2, 6)
2
12
int64


Reshape a 1D array of size 12 into a (3, 4) matrix.


In [45]:
arr = np.array([12,34,56,78,23,21,12,78,90,80,44,33]).reshape(3,4)
arr

array([[12, 34, 56, 78],
       [23, 21, 12, 78],
       [90, 80, 44, 33]])

Flatten a 2D NumPy array.


In [49]:
arr = np.array([[1,2,3,4],[34,56,78,90]])
arr.flatten()

array([ 1,  2,  3,  4, 34, 56, 78, 90])

Convert a NumPy array to a Python list.


In [59]:
arr = np.array([12,21,34,43,65,56])
list = arr.tolist()
print(f"list:{list}")
arr

list:[12, 21, 34, 43, 65, 56]


array([12, 21, 34, 43, 65, 56])

Access the 3rd element of a 1D array.


In [60]:
arr = np.array([1,2,3,4,5,6])
arr[2]

np.int64(3)

Slice the first 3 rows and first 2 columns of a 2D array.


In [64]:
arr = np.arange(12).reshape(2,6)
print(arr)
arr[:3,:2]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([[0, 1],
       [6, 7]])

Select all even numbers from a NumPy array.


In [67]:
arr = np.arange(12).reshape(3,4)
print(arr)

arr[arr%2==0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  2,  4,  6,  8, 10])

Replace all negative values in an array with 0.


In [ ]:
arr = np.array([-2,-3,-5,45,67,89])
print(arr)

arr[arr < 0] = 0
print(arr)



[-2 -3 -5 45 67 89]
[ 0  0  0 45 67 89]


Perform element-wise addition of two arrays.


In [76]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([2,4,5,6])
arr1+arr2

array([ 4,  7,  9, 11])

Perform element-wise multiplication of two arrays.


In [77]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([2,4,5,6])
arr1*arr2

array([ 4, 12, 20, 30])

Compute the dot product of two arrays.


In [ ]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([2,4,5,6])

np.dot(arr1,arr2)


np.int64(66)

Calculate the mean, median, and standard deviation of an array.


In [ ]:
arr = np.array([2,3,4,5])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))


3.5
3.5
1.118033988749895


Find the maximum and minimum values along each column.


In [84]:
arr = np.array([[1, 5, 2],
                [3, 0, 7],
                [4, 8, 6]])
print(arr)

min_value = np.min(arr,axis=0)
max_value = np.max(arr,axis=0)

print(min_value)
print(max_value)

[[1 5 2]
 [3 0 7]
 [4 8 6]]
[1 0 2]
[4 8 7]


Sort a NumPy array.


In [ ]:
arr = np.array([[1, 5, 2],
                [3, 0, 7],
                [4, 8, 6]])

sort_arr = np.sort(arr)
sort_arr



array([[1, 2, 5],
       [0, 3, 7],
       [4, 6, 8]])

Use broadcasting to add a 1D array to each row of a 2D array.


In [91]:
arr1 = np.arange(12).reshape(2,6)

arr2 = np.array([1,2,3,4,5,6])

print(arr1+arr2)

[[ 1  3  5  7  9 11]
 [ 7  9 11 13 15 17]]


Generate an array of 20 random integers between 1 and 100.


In [93]:
arr = np.random.randint(1,100,20)
arr

array([64, 83, 64, 54, 92, 20, 84, 21, 27, 75, 97, 37, 75,  5, 77, 40, 20,
       76, 85, 95], dtype=int32)

Set a random seed and generate random numbers.


In [105]:
arr = np.random.randint(2,size=5)
print(arr)

[1 1 1 1 0]


Shuffle the elements of a NumPy array.


In [100]:
arr = np.array([12,34,5,67,89,12])
np.random.seed(42)
np.random.shuffle(arr)
print(arr)

[12 34 12  5 89 67]


Find unique elements and their counts in an array.


In [110]:
arr = np.array([1,2,2,3,3,3,4,4,4,5,5,5,5,6,6])

unique_element,counts = np.unique(arr,return_counts = True)
print(f"unique Element: {unique_element}")
print(f"Count/frequency: {counts}")

unique Element: [1 2 3 4 5 6]
Count/frequency: [1 2 3 3 4 2]


Stack two arrays vertically and horizontally.


In [116]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([2,4,5,6])

print(f"Vstack: {np.vstack([arr1,arr2])}")
print(f"hstack: {np.hstack([arr1,arr2])}")


Vstack: [[2 3 4 5]
 [2 4 5 6]]
hstack: [2 3 4 5 2 4 5 6]


Split an array into 3 equal parts.


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.split(arr,3))


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Compute the inverse of a square matrix.


In [119]:
arr = np.array([[1,2],[3,4]])

arr_inverse = np.linalg.inv(arr)
print(arr_inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


Calculate eigenvalues and eigenvectors of a matrix.


In [121]:
arr = np.array([[1,2],[3,4]])

eigenvalues,eigenvectors = np.linalg.eig(arr)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors: {eigenvectors}")

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Replace all values greater than the mean with the mean value.

In [125]:
arr = np.array([[1,2],[3,4]])

mean_value = np.mean(arr)

arr[arr >mean_value] = mean_value
print(arr)

[[1 2]
 [2 2]]
